### ISSUE TITLE
Tails Browser of Firefox not working with Meguca.

### ISSUE THREAD

**Issue by amnesiatek** [bakape/meguca#285] opened 2015-09-27 08:55 UTC
I run Tails and tried going on meguca but none of the options work, posting doesnt work. I'm not sure what it is that's stopping it from working since the extensions running are adblock plus, amnesia branding (not sure what that is), Tor button, NoScript (not blokcing scripts on meguca or anywhere), and https everywhere.

**Comment by bakape** [comment] 2015-09-27 09:29
Is Tails based on Firefox 38 ESR by any chance?

**Comment by amnesiatek** [comment] 2015-09-27 09:34
Yes it is.

**Comment by bakape** [comment] 2015-09-27 09:44
Firefox 38 introduced a regression which broke full ECMAScript 5 spec compatibility. This has been fixed in FF 39. Since the bug is already fixed, it is Mozilla's/Tails' duty backport it to their ESRs, not mine. As an immediate workaround you can use the previous version of FF ESR/Tails, which worked fine. Of course the current stable version 41 works fine as well.

**Closed by bakape** 2015-09-27 09:44 UTC
Labels: wontfix
