### ISSUE TITLE
Latest Chrome fucks Meguca a tiny bit

### ISSUE THREAD

**Issue by kipukun** [bakape/meguca#549] opened 2017-06-12 23:54 UTC
Upon updating Chrome to version 59.0.3071.86, the following errors occur:

- Navbar becomes large
- Hovering over images doesn't expand them
- When hovering over a quote, the original post is not displayed

How to replicate
- Visit the site

**Comment by bakape** [comment] 2017-06-13 09:37
This on a touchscreen machine? What OS?

**Comment by kipukun** [comment] 2017-06-13 17:28
This is on a standard laptop (T420s) running Windows 10.

**Comment by bakape** [comment] 2017-06-13 17:55
Works on my Linux machine. I'll boot up and update Win10 and check, if I can reproduce. It seems Chrome is triggering this media query https://github.com/bakape/meguca/blob/master/less/base.less#L283 , but no clue why. Any ideas?

**Comment by kipukun** [comment] 2017-06-13 18:47
It's odd, since looking at my UA string, it says that my pointer device is a mouse. + I've never used this media query before. Maybe a look into the Chrome change-log would provide some insight.

**Comment by bakape** [comment] 2017-06-13 19:03
Since nothing else much supports these, maybe commenting it out would be good enough temp fix.

**Comment by kipukun** [comment] 2017-06-13 19:04
![dance](https://user-images.githubusercontent.com/6733106/27099635-870a936c-5049-11e7-9b44-aec45487d406.gif)

**Comment by kipukun** [comment] 2017-06-13 19:04
We also can't forget the lack of posts showing on hover. What code is used for that?

**Comment by bakape** [comment] 2017-06-13 19:07
Just checked in a win10 VM. Can not reproduce. The fuck is happening? In this case I'd prefer to keep this, for Android Chrome.

>We also can't forget the lack of posts showing on hover. What code is used for that?

The same query, I linked. It hides the entire overlay, that contains the hovered post and image previews.

**Comment by bakape** [comment] 2017-06-14 08:38
What is are the outputs of of `window.matchMedia("(pointer: coarse").matches` and `window.matchMedia("(hover: hover").matches` on the affected machine?

**Comment by bakape** [comment] 2017-06-15 22:24
Now that the hover UI and the larger banner buttons are separate, this bug will only cause big buttons. Fixed enough for me.

**Closed by bakape** 2017-06-15 22:24 UTC
Labels: bug, client

**Comment by kipukun** [comment] 2017-06-15 22:26
sasuga lat
