### ISSUE TITLE
More complex rolls like the ones in Roll20

### ISSUE THREAD

**Issue by DonaldTsang** [bakape/meguca#905] opened 2018-10-07 04:24 UTC
source: https://app.roll20.net/assets/dengine.js?v=123  
beautified: https://ghostbin.com/paste/2n67m  
Reference: https://wiki.roll20.net/Dice_Reference

**Comment by DonaldTsang** [comment] 2018-10-07 14:48
@bakape if you can reverse-engineer it then it can be made into a Python/Go/PHP/JS library

**Comment by bakape** [comment] 2018-10-07 16:34
There is not much to reverse-enginner. The problem is integrating it with
meguca, that is plenty of work. And I don't think there is muh need to
create a separate lib from this. The coupling is too tight for that.

**Comment by Chiiruno** [comment] 2018-10-07 18:45
A lot of these different dice rolls seem pointless for meguca, and too much work to bother with, at least for me.
I'm against this being implemented, it's pointless complexity. (In meguca's case)

**Comment by bakape** [comment] 2018-10-08 07:56
I am not against adding this functionality but not keen enough to implement
it. PRs are welcome and I'll answer any specific questions you have.

**Comment by mission712** [comment] 2018-10-17 18:10
Ghostbin seems dead, but I can try my hand at making a Python library. Are Go and Python interoperable?

**Comment by bakape** [comment] 2018-10-17 18:17
Lol no. Python is too slow and I'm not including any in meguca. You could
write a lib in C/C++, if you want.

**Comment by DonaldTsang** [comment] 2018-10-17 18:40
@mission712 https://app.roll20.net/assets/dengine.js?v=123 is the true sauce, you need to beautify the source code to read it. @bakape okay so Dice-Go is a must... I guess Dice-Py can be used for m712's Blazechan project.

**Comment by DonaldTsang** [comment] 2018-10-17 20:16
@mission712 enjoy https://pastebin.com/X0Zz4Pwy

**Comment by Chiiruno** [comment] 2019-01-23 17:49
Seems dead.
Closing, if @bakape is interested he can reopen.

**Closed by Chiiruno** 2019-01-23 17:49 UTC
Labels: feature
