### ISSUE TITLE
Reflect mod actions when on board index

### ISSUE THREAD

**Issue by Tozuko** [bakape/meguca#647] opened 2018-02-04 02:50 UTC
When you delete a post or ban a poster from a board index page, you don't actually see the changes until you refresh the page. If you do it from within a thread, you see the changes immediately.

Would there be any way to automatically show the mod actions from the non-thread board pages? Even if it's just refreshing the page?

**Comment by bakape** [comment] 2018-02-04 11:39
Duplicate of #537. I'll get around to it eventually, but I'm just one person and there are too many changes planned for meguca.

**Closed by bakape** 2018-02-04 11:39 UTC
